// Generated Sep 13, 2018 11:32:10 AM by Hibernate Tools 3.4.0.CR1
package entities;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * RUser generated by hbm2java
 */
@Entity
@Table(name = "R_USER", catalog = "REMINDER")
public class RUser implements Serializable {

	private int userId;
	private String username;
	private String division;
	private String flAdmin;
	private String password;
	private String email;

	public RUser() {
	}

	public RUser(String username, String password) {
		super();
		this.username = username;
		this.password = password;
	}

	public RUser(int userId, String username) {
		this.userId = userId;
		this.username = username;
	}

	public RUser(int userId, String username, String division, String flAdmin,
			String password, String email) {
		this.userId = userId;
		this.username = username;
		this.division = division;
		this.flAdmin = flAdmin;
		this.password = password;
		this.email = email;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "division", length = 50)
	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	@Column(name = "fl_admin", length = 5)
	public String getFlAdmin() {
		return this.flAdmin;
	}

	public void setFlAdmin(String flAdmin) {
		this.flAdmin = flAdmin;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
