package entities;

// Generated Sep 15, 2018 5:06:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TrReports generated by hbm2java
 */
@Entity
@Table(name = "TR_REPORTS", catalog = "REMINDER")
public class TrReports implements java.io.Serializable {

	private int reportId;
	private String customer;
	private String project;
	private String remarks;
	private String noPo;
	private String marketing;
	private String noInvoice;
	private String nomorPajak;
	private Date tanggalInvoice;
	private Date tanggalTt;
	private Integer term;
	private Date tanggalJthTempo;
	private Long piutangUsaha;
	private Long dpp;
	private Long ppn;
	private Long pph;
	private Long uangMasuk;
	private Date tanggalLunas;

	public TrReports() {
	}

	public TrReports(int reportId) {
		this.reportId = reportId;
	}

	public TrReports(int reportId, String customer, String project,
			String remarks, String noPo, String marketing, String noInvoice,
			String nomorPajak, Date tanggalInvoice, Date tanggalTt,
			Integer term, Date tanggalJthTempo, Long piutangUsaha, Long dpp,
			Long ppn, Long pph, Long uangMasuk, Date tanggalLunas) {
		this.reportId = reportId;
		this.customer = customer;
		this.project = project;
		this.remarks = remarks;
		this.noPo = noPo;
		this.marketing = marketing;
		this.noInvoice = noInvoice;
		this.nomorPajak = nomorPajak;
		this.tanggalInvoice = tanggalInvoice;
		this.tanggalTt = tanggalTt;
		this.term = term;
		this.tanggalJthTempo = tanggalJthTempo;
		this.piutangUsaha = piutangUsaha;
		this.dpp = dpp;
		this.ppn = ppn;
		this.pph = pph;
		this.uangMasuk = uangMasuk;
		this.tanggalLunas = tanggalLunas;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "report_id", unique = true, nullable = false)
	public int getReportId() {
		return this.reportId;
	}

	public void setReportId(int reportId) {
		this.reportId = reportId;
	}

	@Column(name = "customer", length = 150)
	public String getCustomer() {
		return this.customer;
	}

	public void setCustomer(String customer) {
		this.customer = customer;
	}

	@Column(name = "project", length = 150)
	public String getProject() {
		return this.project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	@Column(name = "remarks", length = 50)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "no_po", length = 50)
	public String getNoPo() {
		return this.noPo;
	}

	public void setNoPo(String noPo) {
		this.noPo = noPo;
	}

	@Column(name = "marketing", length = 50)
	public String getMarketing() {
		return this.marketing;
	}

	public void setMarketing(String marketing) {
		this.marketing = marketing;
	}

	@Column(name = "no_invoice", length = 50)
	public String getNoInvoice() {
		return this.noInvoice;
	}

	public void setNoInvoice(String noInvoice) {
		this.noInvoice = noInvoice;
	}

	@Column(name = "nomor_pajak", length = 50)
	public String getNomorPajak() {
		return this.nomorPajak;
	}

	public void setNomorPajak(String nomorPajak) {
		this.nomorPajak = nomorPajak;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tanggal_invoice", length = 26)
	public Date getTanggalInvoice() {
		return this.tanggalInvoice;
	}

	public void setTanggalInvoice(Date tanggalInvoice) {
		this.tanggalInvoice = tanggalInvoice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tanggal_tt", length = 26)
	public Date getTanggalTt() {
		return this.tanggalTt;
	}

	public void setTanggalTt(Date tanggalTt) {
		this.tanggalTt = tanggalTt;
	}

	@Column(name = "term")
	public Integer getTerm() {
		return this.term;
	}

	public void setTerm(Integer term) {
		this.term = term;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tanggal_jth_tempo", length = 26)
	public Date getTanggalJthTempo() {
		return this.tanggalJthTempo;
	}

	public void setTanggalJthTempo(Date tanggalJthTempo) {
		this.tanggalJthTempo = tanggalJthTempo;
	}

	@Column(name = "piutang_usaha", precision = 18, scale = 0)
	public Long getPiutangUsaha() {
		return this.piutangUsaha;
	}

	public void setPiutangUsaha(Long piutangUsaha) {
		this.piutangUsaha = piutangUsaha;
	}

	@Column(name = "dpp", precision = 18, scale = 0)
	public Long getDpp() {
		return this.dpp;
	}

	public void setDpp(Long dpp) {
		this.dpp = dpp;
	}

	@Column(name = "ppn", precision = 18, scale = 0)
	public Long getPpn() {
		return this.ppn;
	}

	public void setPpn(Long ppn) {
		this.ppn = ppn;
	}

	@Column(name = "pph", precision = 18, scale = 0)
	public Long getPph() {
		return this.pph;
	}

	public void setPph(Long pph) {
		this.pph = pph;
	}

	@Column(name = "uang_masuk", precision = 18, scale = 0)
	public Long getUangMasuk() {
		return this.uangMasuk;
	}

	public void setUangMasuk(Long uangMasuk) {
		this.uangMasuk = uangMasuk;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tanggal_lunas", length = 23)
	public Date getTanggalLunas() {
		return this.tanggalLunas;
	}

	public void setTanggalLunas(Date tanggalLunas) {
		this.tanggalLunas = tanggalLunas;
	}

}
